[package]
name = "ascii_game_project_j1"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.5"
clap = { version = "4.5.31", features = ["derive"] }
build_html = "2.6.0"
htmlescape = "0.3"
